package com.storageauctions.dev.ServiceManager;

import java.util.Date;

public class Auction {

    public int auct_id;
    public int facility_id;
    public int auction_online_bid_id;
    public int status;
    public String failed_reason;
    public String descr;
    public Date time_start;
    public String time_st_zone;
    public Date time_end;
    public String time_end_zone;
    public String amount_owed;
    public double fees;
    public String tenant_name;
    public int unit_number;
    public int unit_size;
    public String lock_tag;
    public Date time_created;
    public Date time_updated;
    public int bid_count;
    public int winner_code;
    public double seller_fee;
    public double buyer_fee;
    public int emailed;
    public String terms;
    public int queue_flag;
    public String auction_id;
    public AuctionMeta meta;
    public double tax;
    public String remote_id;
    public String source_id;
    public double reserve;
    public int bid_schedule_id;
    public int alt_unit_number;
    public int batch_email;
    public String title;
    public String facility_name;
    public String address;
    public String city;
    public String state_code;
    public int user_id;
    public double amount;
    public int bid_user_id;
    public int media_auction_id;
    public String photo_path_size0;
    public String photo_path_size1;
    public String photo_path_size2;
    public String photo_path_size3;
    public int view_count;
    public String os_date;
    public String os_time;
    public String url;
    public String group;
    public String type;
    public String category;
}
