# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StorageAuctions' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for StorageAuctions
	pod 'IQKeyboardManager'
	pod 'ProgressHUD'
	pod 'AFNetworking'
	pod 'LGSideMenuController'
	pod 'GoogleMaps'
  	pod 'GooglePlaces'
  	pod 'LMGeocoder'
    pod 'PopupDialog', '0.5.0'
    pod 'SDWebImage'
    pod 'DateTools'

end
